### ISSUE TITLE
SMTP with TLS is not enabled

### ISSUE THREAD

**Issue by natasha1234567890** [juanluisbaptiste/docker-postfix#101]
### Discussed in https://github.com/juanluisbaptiste/docker-postfix/discussions/100

<div type='discussions-op-text'>

<sup>Originally posted by **natasha1234567890** June 12, 2023</sup>
SMTP with TLS is not really enabled as you can see from capabilities advertised by the server.
There should be '250-STARTTLS'

How can I enable TLS?

nh@helenubuntu:~/docker-postfix$ telnet localhost 25
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
220 mailhog.example ESMTP MailHog
ehlo kk
250-Hello kk
250-PIPELINING
250 AUTH PLAIN
quit
221 Bye
</div>

**Comment by juanluisbaptiste** [comment]
This is intentional, for the sake of simplicity when using this image, read the docs.
