### ISSUE TITLE
Send a Test Email

### ISSUE THREAD

**Issue by joel72265** [juanluisbaptiste/docker-postfix#102]
hi, thank you for the image.

New Feature: is there a way to test postfix functionality like to 'Send a Test email' from postfix

**Comment by juanluisbaptiste** [comment]
To test if your email is working, connect to the postfix container and use the `mail` command to send a test email.

**Comment by joel72265** [comment]
When I connect to the container and run the mail command, it shows '**No mail for root**'. (please excuse my ignorance)

**root@postfix-relay-01** [ ~ ]# docker exec -it 42e7249d3e82 /bin/bash
**bash-5.1**# mail
No mail for root

**Comment by mstenz** [comment]
> **bash-5.1**# mail

Nobody said you should execute mail without any commands. Please see for example here: https://phoenixnap.com/kb/linux-mail-command

**Comment by joel72265** [comment]
but my system is a Photon OS not RHEL based, thank you

**Comment by mstenz** [comment]
> but my system is a Photon OS not RHEL based, thank you

this is inside the container, it doesn't matter what OS you have.
