### ISSUE TITLE
Postfix cannot find \/etc\/postfix\/sasl_passwd

### ISSUE THREAD

**Issue by bencomp** [juanluisbaptiste/docker-postfix#11]
Since recreating the postfix container (after a pull) I cannot send emails anymore, which used to work with the exact same settings.

The `/var/log/maillog` shows that Postfix cannot find the password file:

    postfix_1    | Mar 10 16:51:58 ac84ee08fcbb postfix/smtp[156]: warning: hash:\/etc\/postfix\/sasl_passwd is unavailable. open database \/etc\/postfix\/sasl_passwd.db: No such file or directory

I think the recent merge of #7 has caused this: `postconf` doesn't appear to unescape the `\/`, whereas `sed` probably did. When I manually change the line

    smtp_sasl_password_maps = hash:\/etc\/postfix\/sasl_passwd

to

    'smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd

(and not restart the container!) emails are sent again, including ones in the queue.

**Comment by juanluisbaptiste** [comment]
Ooops, let me review this...

**Comment by juanluisbaptiste** [comment]
You are right, pushing a fix now.

**Comment by juanluisbaptiste** [comment]
Done.

**Comment by bencomp** [comment]
Thanks for the quick response!
