### ISSUE TITLE
Can not build on arm32v7

### ISSUE THREAD

**Issue by Legion2** [juanluisbaptiste/docker-postfix#13]
Trying to use this on Raspberry Pi.
But get `No package epel-release available.` error when trying to build the docker image on Raspberry Pi.

**Comment by juanluisbaptiste** [comment]
Hi,

I have not tested this on any other platform other than x86_64 nor plan to, but PR is welcome.

**Comment by Legion2** [comment]
I currently building a new Dockerfile based on Debian using your configurations

**Comment by juanluisbaptiste** [comment]
Probably the repos needed aren't available for that arch, and this image currently does not support it and will not for the foreseeable future.

As I said, PR welcome.
