### ISSUE TITLE
License for the project ?

### ISSUE THREAD

**Issue by maykelange** [juanluisbaptiste/docker-postfix#27]
Hello and thank you for your work.

We would like to use your image, however we could not find any licensing information.

If you intended for your work to be open source, you can add a license in your README, or a separate license file. Github has a great choose your licence page [https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository).

If you want to retain copyright, it would be helpful if the README contained a copyright notice.

**Comment by juanluisbaptiste** [comment]
Done.
