### ISSUE TITLE
Sending e-mail without getting blocked

### ISSUE THREAD

**Issue by ViRb3** [juanluisbaptiste/docker-postfix#30]
This issue is not specific to this Docker image, but it happens because of Postfix and I really hope I can find a solution.

I want to use this project to send verification e-mails through a newly created e-mail account. I tried Gmail, Outlook, even Yandex Mail. Unfortunately, each one of them detects Postfix as a spam/bot, and requests phone verification to proceed, something I want to avoid. If I use a mainstream e-mail client like Outlook, everything works, which leads me to believe that it is something specific to Postfix they are detecting. Do you know how I could bypass this detection?

Thank you

**Comment by juanluisbaptiste** [comment]
No idea, sorry. Doing a quick search I found this, maybe it can help: https://www.digitalocean.com/community/questions/email-sent-to-gmail-is-flagged-as-spam
