### ISSUE TITLE
Postfix can't send email to the same domain name email address (G Suite)

### ISSUE THREAD

**Issue by dtcooper** [juanluisbaptiste/docker-postfix#35]
Using GMail for my G Suite account, for example `mydomain.com` below, I run the container with the following environment variables:

```
SMTP_SERVER=smtp.gmail.com
SMTP_PORT=587
SMTP_USERNAME=no-reply@mydomain.com
SMTP_PASSWORD=topsecret
SERVER_HOSTNAME=mydomain.com
```

Now if try to send an email to `user@mydomain.com`, I get the following error,

```
Oct 11 02:55:23 c2068577d527 postfix/smtpd[96]: NOQUEUE: reject: RCPT from carb_admin_run_1bc21d8a4fd6.carb_default[****]: 550 5.1.1 <user@mydomain.com>: Recipient address rejected: User unknown in local recipient table; from=<no-reply@mydomain.com> to=<user@mydomain.com> proto=ESMTP helo=<[****]>
```

Per the Postfix documentation on `mydestination`, it should contain the list of domains whose emails are hosted on the local Postfix server so that they are handled internally and not relayed out to external systems. Since the container is **not** using Postfix to receive mail, we should set `mydestination` to `localhost` only.

So [line 32 in `run.py`](https://github.com/juanluisbaptiste/docker-postfix/blob/c55bcb70acaa7222e8bd97462706cf72d45fea20/run.sh#L32) should be changed from,

```
add_config_value "mydestination" '$myhostname'
```

to

```
add_config_value "mydestination" 'localhost'
```

Thanks!

**Comment by dtcooper** [comment]
Added two PRs, one on master and one on the `migrate_to_alpine` branch. Thanks again!

**Comment by juanluisbaptiste** [comment]
Hi @dtcooper , thanks for reporting and for the PR, I will test it this weekend, sorry for the delay.

**Comment by dtcooper** [comment]
Any update? Would love to use this as a container without forking in my project. 😄

**Comment by dtcooper** [comment]
Friendly ping. 👯‍♀️

**Comment by juanluisbaptiste** [comment]
@dtcooper Merged, thanks.
