### ISSUE TITLE
Is supported TLS encryption(Let's Encrypt) and submission port?

### ISSUE THREAD

**Issue by falconws** [juanluisbaptiste/docker-postfix#40]
Is this docker-postfix supported TLS encryption and submission port(587/tcp) with let's encrypt?
If yes, I think run.sh is missing config value like below.

```
add_config_value "smtpd_tls_cert_file" "/etc/postfix/signed.crt"
add_config_value "smtpd_tls_key_file" "/etc/postfix/domain.key"
add_config_value "smtpd_tls_security_level" "may"
```

Maybe these parameters are needed for Let's Encrypt and submission port.

**Comment by juanluisbaptiste** [comment]
Hi @falconws 

No it does not support this, feel free to create a PR.

**Comment by falconws** [comment]
I see.
Thank you for your response.

**Comment by falconws** [comment]
Hi @juanluisbaptiste 

By the way, can postfix setup submission port(587/tcp) without a certificate(In other words, without TLS encryption)?
And can docker-postfix do that?
My purpose is that bypass outbound port 25 blocking on AWS.
https://aws.amazon.com/premiumsupport/knowledge-center/ec2-port-25-throttle/


Please teach me.
Thanks.

**Comment by juanluisbaptiste** [comment]
> Hi @juanluisbaptiste
> 
> By the way, can postfix setup submission port(587/tcp) without a certificate(In other words, without TLS encryption)?
> And can docker-postfix do that?
> My purpose is that bypass outbound port 25 blocking on AWS.
> https://aws.amazon.com/premiumsupport/knowledge-center/ec2-port-25-throttle/
> 
> Please teach me.
> Thanks.

Have you read the documentation ? the default port is 587.

**Comment by falconws** [comment]
@juanluisbaptiste 
Sorry, understood.

**Comment by falconws** [comment]
@juanluisbaptiste 
> Have you read the documentation ? the default port is 587.

You said that, but implementation is
https://github.com/juanluisbaptiste/docker-postfix/blob/master/Dockerfile#L18
> EXPOSE 25

https://github.com/juanluisbaptiste/docker-postfix/blob/master/docker-compose.yml#L6

```
expose:
  - "25"
```

It looks like default port is 25.
But README.md is
> SMTP_PORT (Optional, Default value: 587) Port address of the SMTP server to use.

Why?

**Comment by juanluisbaptiste** [comment]
You are looking at the wrong place, see [this line](https://github.com/juanluisbaptiste/docker-postfix/blob/29b356bb2b3c2a5a39452826c8c02af3017dc39d/run.sh#L24) on the entrypoint.
