### ISSUE TITLE
451 4.3.2 Internal server error (in reply to RCPT TO command)) 

### ISSUE THREAD

**Issue by xzf16** [juanluisbaptiste/docker-postfix#43]
I try to use this postfix relay docker to do the smtp relay for redmine.

But I found the e-mail can't send out, and it returns 451 4.3.2 Internal server error (in reply to RCPT TO command)) .

Can anyone help me to solve this problem.

BTW, the smtp server is a Chinese local smtp service supplier.

**Comment by juanluisbaptiste** [comment]
Hi, this is not a support forum, you should check your server logs.
