### ISSUE TITLE
Error building alpine image

### ISSUE THREAD

**Issue by Diak** [juanluisbaptiste/docker-postfix#45]
Hi,

I can't build alpine image, i've got this error : 
```
$ podman build .
STEP 1: FROM alpine
--> Using cache b3b48f001ff6d8634c699b1ea2547db81459a6399612499ec9784d0ecd6c8e95
--> b3b48f001ff
STEP 2: RUN apk update &&     apk add bash gawk cyrus-sasl cyrus-sasl-plain cyrus-sasl-login cyrus-sasl-crammd5 mailx     perl supervisor postfix rsyslog &&     rm -rf /var/cache/apk/* &&     mkdir -p /var/log/supervisor/ /var/run/supervisor/ &&     sed -i -e 's/inet_interfaces = localhost/inet_interfaces = all/g' /etc/postfix/main.cf
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
v3.13.0-6-gc9c6964928 [https://dl-cdn.alpinelinux.org/alpine/v3.13/main]
v3.13.0-10-gb379e70abc [https://dl-cdn.alpinelinux.org/alpine/v3.13/community]
OK: 13870 distinct packages available
ERROR: unable to select packages:
  cyrus-sasl-plain (no such package):
    required by: world[cyrus-sasl-plain]
Error: error building at STEP "RUN apk update &&     apk add bash gawk cyrus-sasl cyrus-sasl-plain cyrus-sasl-login cyrus-sasl-crammd5 mailx     perl supervisor postfix rsyslog &&     rm -rf /var/cache/apk/* &&     mkdir -p /var/log/supervisor/ /var/run/supervisor/ &&     sed -i -e 's/inet_interfaces = localhost/inet_interfaces = all/g' /etc/postfix/main.cf": error while running runtime: exit status 1
```
Have i missed something or is it a version problem ?

**Comment by Diak** [comment]
If I refer to https://pkgs.alpinelinux.org/packages?name=cyrus-sasl-plain&branch=v3.12, this package existed in v3.12 version of alpine but not anymore in v3.13.

**Comment by juanluisbaptiste** [comment]
Hi @Diak , thanks for the report. For now I will pin alpine version to v3.12 while I investigate how to handle the removal of that package.

**Comment by annisk** [comment]
I was able to work around this by removing `cyrus-sasl-plain` from the package list and changing
```
add_config_value "smtp_sasl_password_maps" "hash:/etc/postfix/sasl_passwd"
```
to
```
add_config_value "smtp_sasl_password_maps" "lmdb:/etc/postfix/sasl_passwd"
```

**Comment by Diak** [comment]
Ok I'll test this week-end. Thanks.

**Comment by Diak** [comment]
I tried but when i change to alpine 3.13 (or 3.13.1 or latest) i have a strange ssl certificate problem : 
```
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
140471547386696:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1913:
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.13/main: Permission denied
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/main: No such file or directory
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
140471547386696:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1913:
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.13/community: Permission denied
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/community: No such file or directory
2 errors; 14 distinct packages available
Error: error building at STEP "RUN apk update &&     apk add bash gawk cyrus-sasl cyrus-sasl-login cyrus-sasl-crammd5 mailx     perl supervisor postfix rsyslog &&     rm -rf /var/cache/apk/* &&     mkdir -p /var/log/supervisor/ /var/run/supervisor/ &&     cp -a /var/spool/postfix /var/spool/postfix.cache &&     sed -i -e 's/inet_interfaces = localhost/inet_interfaces = all/g' /etc/postfix/main.cf": error while running runtime: exit status 2
```
With alpine 3.12 i have no problem........

**Comment by juanluisbaptiste** [comment]
> I tried but when i change to alpine 3.13 (or 3.13.1 or latest) i have a strange ssl certificate problem :
> 
> ```
> fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
> 140471547386696:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1913:
> ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.13/main: Permission denied
> WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/main: No such file or directory
> fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
> 140471547386696:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1913:
> ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.13/community: Permission denied
> WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/community: No such file or directory
> 2 errors; 14 distinct packages available
> Error: error building at STEP "RUN apk update &&     apk add bash gawk cyrus-sasl cyrus-sasl-login cyrus-sasl-crammd5 mailx     perl supervisor postfix rsyslog &&     rm -rf /var/cache/apk/* &&     mkdir -p /var/log/supervisor/ /var/run/supervisor/ &&     cp -a /var/spool/postfix /var/spool/postfix.cache &&     sed -i -e 's/inet_interfaces = localhost/inet_interfaces = all/g' /etc/postfix/main.cf": error while running runtime: exit status 2
> ```
> 
> With alpine 3.12 i have no problem........
> 
> and --tls-verify=false doesn't change anything

@Diak I just did a successful rebuild using 3.13 removing the cyrus-sasl-plain package, that sounds more of a temporary issue with the repository.

**Comment by Diak** [comment]
Ok I'll try again tomorrow so :)

**Comment by juanluisbaptiste** [comment]
> I was able to work around this by removing `cyrus-sasl-plain` from the package list and changing
> 
> ```
> add_config_value "smtp_sasl_password_maps" "hash:/etc/postfix/sasl_passwd"
> ```
> 
> to
> 
> ```
> add_config_value "smtp_sasl_password_maps" "lmdb:/etc/postfix/sasl_passwd"
> ```

This worked for me too, thanks.

**Comment by Diak** [comment]
Ok my problem with alpine 3.13 seems to come with the fact than since 3.13 version they change repo from http:// to https:// and it doesn't seem to work because of my company proxy.
So I'll later when the problem will be fixed on alpine.

Do you want me to close this ticket now it seems to be fixed thanks to @annisk ?

**Comment by juanluisbaptiste** [comment]
Not yet, I first have to do the code changes and release a new image, and before that I need to close issue #16 first and make the alpine image the main one.

**Comment by juanluisbaptiste** [comment]
Fix pushed, closing this issue.
