### ISSUE TITLE
smtp_tls_security_level without port 465?

### ISSUE THREAD

**Issue by roy-bentley** [juanluisbaptiste/docker-postfix#48]
Hi there,

I have recently set up your container to work as a relay to Office365 Mail/Exchange Online. In doing so, I found that the `smtp_tls_security_level` setting was required, but both without `smtp_tls_wrappermode` and not on port 465. 

https://github.com/juanluisbaptiste/docker-postfix/blob/9b1d5b47a70482afacbaaee5a75469036cdf36ef/run.sh#L41-L44

Would you be willing to accept a PR to add an environment variable to set `smtp_tls_security_level`?

Also, per the Postfix docs, `smtp_tls_security_level` should be used in place of [`smtp_use_tls`](http://www.postfix.org/postconf.5.html#smtp_use_tls) for Postfix 2.3 and above. I commented this out with no ill effect (I believe  `smtp_tls_security_level` implies `smtp_use_tls`), but I don't have anywhere to test this...

**Comment by juanluisbaptiste** [comment]
Hi,

> I have recently set up your container to work as a relay to Office365 Mail/Exchange Online. In doing so, I found that the `smtp_tls_security_level` setting was required, but both without `smtp_tls_wrappermode` and not on port 465.
> 

AFAIK Office 365 uses TLS over port 587, 465 port is for SMTPS (SSL) and needs those options, so the current default settings should work.

> Also, per the Postfix docs, `smtp_tls_security_level` should be used in place of [`smtp_use_tls`](http://www.postfix.org/postconf.5.html#smtp_use_tls) for Postfix 2.3 and above. I commented this out with no ill effect (I believe `smtp_tls_security_level` implies `smtp_use_tls`), but I don't have anywhere to test this...

This has to be tested first to be sure it does not break current setups.

**Comment by juanluisbaptiste** [comment]
Closing for lack of answer.
