### ISSUE TITLE
"mynetworks" env variable

### ISSUE THREAD

**Issue by mirzawaqasahmed** [juanluisbaptiste/docker-postfix#6]
Hi,
Is there a way to add "mynetworks" setting during using env variable?

Thanks in advance...

**Comment by juanluisbaptiste** [comment]
Hi,

No, it currently only supports whats on the README file. PR's welcome.

**Comment by juanluisbaptiste** [comment]
This is being implemented on issue #10

**Comment by xtrasimplicity** [comment]
As the PR for #10  has been merged, maybe this should be closed? :)

**Comment by juanluisbaptiste** [comment]
Sure.
