### ISSUE TITLE
Feature request: Postfix username + password authentication

### ISSUE THREAD

**Issue by rjbaat** [juanluisbaptiste/docker-postfix#64]
Hi, 
Is there an easy way to add postfix local authentication?
I want to use this togheter with a Wordpress container, but that needs to point to a smtp server with username and password. 

So it becomes like: 

--> client (downstream) --> postfix:25 (with local auth) --> external SMTP server (with auth)(upstream)

**Comment by juanluisbaptiste** [comment]
Hi @rjbaat , this container does not support local authentication nor we plan to.

Can you just not set a username and password on the Wordpress plugin ? or setting it to whatever value as the container will not use it.

**Comment by juanluisbaptiste** [comment]
Closing because of lack of answer.
