### ISSUE TITLE
main.cf missing

### ISSUE THREAD

**Issue by RyanMesser** [juanluisbaptiste/docker-postfix#78]
Hey,
On startup of this container it states /etc/postfix/main.cf is missing, is there something I'm missing?

Thanks

**Comment by juanluisbaptiste** [comment]
@RyanMesser please respect the instructions when reporting a bug, and those instructions say, issues are *not* a problem-solving forum, you can use the discussions for that.

**Comment by RyanMesser** [comment]
I didn't see them, when I posted so it's nothing about "respect". 

Anyway I have resolved, and shan't be using this image in future.
