### ISSUE TITLE
Container not starting.

### ISSUE THREAD

**Issue by ljacobo** [juanluisbaptiste/docker-postfix#89]
Hi,

I am trying to setup the outgoing notifications of OTRS with de Postfix container but the container is not starting and the logs tells me:

> SMTP_SERVER is not set

Everything is set it up in the .env file.

How can I work around this?

Thanks.

**Comment by juanluisbaptiste** [comment]
You must have an issue with your environment variables setup, or you aren't setting that mandatory variable.

**Comment by ThomasHineXYZ** [comment]
I am having this issue

Using the `.env.example` file, copying it to `.env`
<img width="497" height="136" alt="Image" src="https://github.com/user-attachments/assets/aa744146-f103-44d3-92c6-f9f0dedf31e1" />
