### ISSUE TITLE
Domain transport limit

### ISSUE THREAD

**Issue by rusomenace** [juanluisbaptiste/docker-postfix#90]
As a company request my postfix needs to be limited to send emails to certain specific domains.
In the traditional instalation this can be achieved adding this to the main.cf at the end of the file:
`transport_maps = texthash:/etc/postfix/transport`

Then you need to edit /etc/postfix/transport and add something like this:
`example.com smtp:`
`* error:only mail to example.com will be delivered`

The question is, how this can be achieved via variables, is it possible?

Thanks

**Comment by juanluisbaptiste** [comment]
Hi,

No it cannot be done right now.
